ay_connect/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponse
import os

from ninja import NinjaAPI
from vehicle.api import api 

from stock_app.api import  stock_api
from Service_request.api import servicerequest_api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',namespace='core')),
   
    path('accounts/', include('accounts.urls',namespace='accounts')),
	
    path('setup/', include('setup.urls')),
  
    path('pricelist/', include('pricelist_update.urls')),

    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('stock/',include('stock_app.urls',namespace='stock')),
    path('Service_request/', include('Service_request.urls', namespace='Service_request')),
    # path('itemPublishing/',include('stock_app.urls',namespace='itemPublishing')),
    path('api/', api.urls),  
    path('api/stock/', stock_api.urls), 

    path('api/servicerequest/', servicerequest_api.urls),
 
    re_path(r'^fp/', include('django_drf_filepond.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENV != "PROD":
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

core/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import *
app_name = 'core'


urlpatterns = [
    path('', views.login, name='login'),
    path('user_announcement', views.user_announcement, name='user_announcement'),
    path('home', IframeView.as_view(), name='home_iframe'),
    path('logout', views.logout, name='logout'),
    path('get_all_columns/<model_name>', views.get_all_columns, name='get_all_columns'),
    path('get_select_options/<model_name>', views.get_select_options , name='get_select_options'),
    path('change_user_inventory/<inv_id>', views.change_user_inventory , name='change_user_inventory'),
    path('upload_product_data_dictionary/', views.upload_product_data_dictionary , name='upload_product_data_dictionary'),
    path('close_page', views.close_page, name='close_page'),

]

setup/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


app_name = 'setup'
router = routers.DefaultRouter()
router.register(r'template_list', views.TemplateContentViewSet, basename="template_list")


urlpatterns = [
    path('api/', include(router.urls)),
    path('template',views.TemplateContentView.as_view(), name='template'),
    path('action/<action_type>/<row_id>', views.TemplateContentView.as_view(), name='template'),
    path('action/<action_type>', views.TemplateContentView.as_view(), name='template'),

    path('template-view', views.template_view , name='template-view'),
    path('template-api', views.TemplateHTMLApi.as_view() , name='template-api'),
    path('template-list', views.template_list_view , name='template-list'),
    path('template-save-api', views.TemplateSaveApi.as_view() , name='template-save-api'),
    path('conc_prog',views.ConcProgView, name='conc_prog'),
    path('conc_prog_invtr',views.ConcProgInvtrView, name='conc_prog_invtr'),
    path('conc_prog_pdf',views.ConcProgPdfView, name='conc_prog_pdf'),
    path('get-input',views.ConcProgInputDataView, name='get-input'),
    path('refresh_report',views.refresh_report, name='refresh_report'),
    path('add-concprog',views.AddConcProgView, name='add-concprog'),
    path('pdf',views.download_file, name='pdf'),
    path('email-via-template', views.TemplateHTMLEmailApi.as_view() , name='email-via-template'),
    path('exec_sql', views.ExecSql.as_view() , name='exec_sql'),

    path('customer_dms', views.CustomerDmsView.as_view(), name='customer_dms'),
    path('dms_records', views.DmsRecordsView, name='dms_records'),
    path('trip_details', views.TripDetailsView, name='trip_details'),
    path('documentation_details', views.DocumentationDetailsView, name='documentation_details'),
]

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from django.shortcuts import resolve_url, reverse
from core.utils import form_elements, get_model_obj, get_loginuser_details
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.conf import settings
from ldap3 import Server, Connection, ALL
from django.contrib import messages, auth
from django.utils.decorators import method_decorator

from .auth_backend import ForceAuth
from django.http import JsonResponse
from core.models import UserProfile
from .ldap import parseLdapUserDetails
from rest_framework import viewsets, filters
from django_filters.rest_framework import DjangoFilterBackend
from core.models import *
from django.apps import apps
from accounts.helpers import get_dynamic_menu, get_all_menu
from rest_framework import views as DRF_views, response
from .serializers import *
import json

# Create your views here.
def imitate(request):
    if request.method == 'GET':
        username = request.GET['u'].lower()
        user = ForceAuth.authenticate(request, request, username=username)
        res = auth.login(request, user, backend='accounts.auth_backend.ForceAuth')
        return redirect('index')
    else:
        JsonResponse('Error', safe=False)

    return render(request, resolve_url( "core:home_iframe") )
def login(request):
    
    # # stop
    if request.user.is_authenticated:
        return redirect( resolve_url( "core:home_iframe") )
        
    if request.method == 'POST':
        username = request.POST['username'].upper().strip()
        password = request.POST['password']
        
        print(settings.LDAP_URL)
        settings.AUTH_LDAP_BIND_DN = 'alyousuf\\' + str(username)
        settings.AUTH_LDAP_BIND_PASSWORD = password
        server = Server(settings.LDAP_URL)
        
        # Django Authentication Backend
        user = auth.authenticate(username=username, password=password)
        
        request.session['username'] = username
        
        # if user is None or settings.ENV=='PROD':
        #     c = Connection(server, user='alyousuf\\' + str(username), password=password)

        #     try:
        #         is_ldap_user = c.bind()
        #         pass
        #     except Exception as e:
        #         is_ldap_user = False
        #     print('is_ldap_user--->',is_ldap_user)
        #     if is_ldap_user:
        #         user = auth.authenticate(username=username, password=password)
        #         fetchUserDetailsFromLDAP(username,password)
        #         u = User.objects.get(username=username)
        #         u.set_password(password)
        #         u.save()

        #     user = auth.authenticate(username=username, password=password)

        if user is not None:

            # c = Connection(server, user='alyousuf\\' + str(username), password=password)
            # try:
            #     is_ldap_user = c.bind()
            #     pass
            # except Exception as e:
            #     is_ldap_user = False
            # print('is_ldap_user-->',is_ldap_user)
            # if is_ldap_user:
            #     user = auth.authenticate(username=username, password=password)
            #     fetchUserDetailsFromLDAP(username,password)
            #     u = User.objects.get(username=username)
            #     u.set_password(password)
            #     u.save()
            
            auth.login(request, user)
            request.session['user'] = username
            user_tenant = UserOrganisationInventory.objects.filter(user=user.id).first()
            request.session["tenant_disabled"] = "0"
            if user_tenant==None:
                tenant = None
            else:
                tenant = None if not user_tenant.inventory else user_tenant.inventory.pk
            request.session['tenant'] = tenant
            request.session['emp_id'] = UserProfile.objects.get(user_id=user.id).employee_id
            request.session['username'] = UserProfile.objects.get(user_id=user.id).user_name
            request.session['role'] = '' if not user_tenant else user_tenant.role.pk
            return redirect(resolve_url( "core:user_announcement"))
        else:
            messages.error(request, 'Incorrect Username or Password')
            return redirect(resolve_url( "core:login"))
    else:
        announcements = AnnouncementsSerializer(Announcements.objects.all(),many=True).data
        events = EventsSerializer(Events.objects.all(),many=True).data
        data = {
            'login_form_url' : resolve_url( "core:login"),
            'announcements':announcements,
            'events' :events
        }
        return render(request, 'core/login.html', context=data)
    
@method_decorator(login_required, name='dispatch')
class IframeView(View):
    
    def get(self, request):
        all_menus = get_all_menu(request)
        user_accessible_menus = get_dynamic_menu(request.user.id)
        user_inventories = UserOrganisationInventory.objects.filter(user=request.user.id)
        inv_array = []
        visited_arr = []

        for user_inv in user_inventories:
            if user_inv.inventory:
                inv_org_type = user_inv.inventory.org_type or None
                if user_inv.inventory.pk not in visited_arr:
                    inv_details = {'org_id': user_inv.inventory.operating_unit_id_id, 'inv_id':user_inv.inventory.pk, 'inv_name':user_inv.inventory.organization_name, 'inv_org_type':inv_org_type,'loc_code':user_inv.inventory.organization_code}
                    inv_array.append(inv_details)
                visited_arr.append(user_inv.inventory.pk)
            # else:
            #     emp_id = request.session.get('emp_id')
            #     username = request.session.get('user')
            #     user_locations = list(UserLocLevels.active_objects.filter(user_name=username).order_by('location_code').values_list('location_code', flat=True).distinct())
            #     ar_locations = ARLocations.objects.filter(loc_code__in = user_locations).distinct('loc_code').order_by('loc_code')
            #     user_locations_obj = UserLocLevels.active_objects.filter(user_name=username).order_by('location').distinct('location')
            #     # inv_array = []
            #     for loc in user_locations_obj:
            #         if not any(d['inv_id'] == loc.location_code for d in inv_array):
            #             inv_details = {'inv_id':loc.location_code, 'inv_name':loc.location, 'inv_org_type':'RECEIPT','loc_code':loc.location_code}
            #             inv_array.append(inv_details)
            #     print('user_locations--->',user_locations)
            #     if(user_locations!=[]):
            #         request.session['location']  = user_locations[-1] if request.session.get('location')==None else request.session.get('location')
            #     else: 
            #         request.session['location']  = None    
        data = {'menu':all_menus,'user_menus':user_accessible_menus,'user_inv_array':inv_array,'APP_VERSION':settings.APP_VERSION, 'roles_json': json.dumps({"roles": [item.role.identifier for item in user_inventories if item.role.identifier is not None]})}
        return render(request, "core/iframe.html", context=data)

def logout(request):
    auth.logout(request)
    messages.success(request, 'You are now logged out')
    return redirect(resolve_url( "core:login"))
 
def user_announcement(request):
    all_menus = get_all_menu(request)
    user_accessible_menus = get_dynamic_menu(request.user.id)
    if request.method == 'POST':
        print("Yaha aaya")
        
        # username = request.POST['username']
        # password = request.POST['password']
        
        # print(settings.LDAP_URL)
        # settings.AUTH_LDAP_BIND_DN = 'alyousuf\\' + str(username)
        # settings.AUTH_LDAP_BIND_PASSWORD = password
        # server = Server(settings.LDAP_URL)
        
        # # Django Authentication Backend
        # user = auth.authenticate(username=username, password=password)
        
        
        # if user is None:
        #     c = Connection(server, user='alyousuf\\' + str(username), password=password)

        #     try:
        #         is_ldap_user = c.bind()
        #         pass
        #     except Exception as e:
        #         is_ldap_user = False
        #     print('is_ldap_user--->',is_ldap_user)
        #     if is_ldap_user:
        #         user = auth.authenticate(username=username, password=password)
        #         fetchUserDetailsFromLDAP(username,password)
        #         u = User.objects.get(username=username)
        #         u.set_password(password)
        #         u.save()

        #     user = auth.authenticate(username=username, password=password)

        # if user is not None:

        #     # c = Connection(server, user='alyousuf\\' + str(username), password=password)
        #     # try:
        #     #     is_ldap_user = c.bind()
        #     #     pass
        #     # except Exception as e:
        #     #     is_ldap_user = False
        #     # print('is_ldap_user-->',is_ldap_user)
        #     # if is_ldap_user:
        #     #     user = auth.authenticate(username=username, password=password)
        #     #     fetchUserDetailsFromLDAP(username,password)
        #     #     u = User.objects.get(username=username)
        #     #     u.set_password(password)
        #     #     u.save()
            
        #     auth.login(request, user)
        #     request.session['user'] = username
        #     user_tenant = UserOrganisationInventory.objects.filter(user=user.id).first()
        #     request.session["tenant_disabled"] = "0"
        #     if user_tenant==None:
        #         tenant = None
        #     else:
        #         tenant = None if not user_tenant.inventory else user_tenant.inventory.pk
        #     request.session['tenant'] = tenant

core/templates/core/announcements.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>AY  Connect | User Announcements</title>
    {% load static %}
    <!-- Google Font: Source Sans Pro -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
    />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="{% static 'plugins/fontawesome-free/css/all.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
      crossorigin="anonymous"
    />
    <!-- icheck bootstrap -->
    <link
      rel="stylesheet"
      href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}"
    />
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}" />
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'js/adminlte.min.js' %}"></script>
    <script
      type="module"
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
    ></script>
    <style>
      ion-icon {
        font-size: 64px;
        color: #fff;
        --ionicon-stroke-width: 16px;
      }
      #myVideo {
        position: fixed;
        margin: 0;
        padding: 0;
        min-width: 100%;
        min-height: 100%;
      }
    </style>
  </head>

  <body>
    <div class="row m-0" style="width: 100vw; height: 100vh;">
      <video autoplay muted loop id="myVideo">
        <source src={% static "videos/2.mp4"%} type="video/mp4" />
      </video>
      <div
        class="col-8 d-flex justify-content-center align-items-center"
        style="height: 100vh; box-sizing: border-box; padding: 0 4px;background: rgb(255 255 255 / 37%);"
      >
        <form action="#" method="post" style="background: rgb(255 255 255 / 37%);
        height: 300px;">
          {% csrf_token %}
          <div class="row m-4 pl-5">
            <style>
              .tile {
  color: white;
  padding: 10px;
  position: relative;
  cursor: pointer;
  transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;
}
.tile--expanded {
  z-index: 1000;
}
.tile--red {
  background-color: #EC644C;
}
.tile--blue {
  background-color: #3498DB;
}
.tile--purple {
  background-color: #9B59B6;
}
.tile--orange {
  background-color: #F57C00;
}
.tile--green {
  background-color: #2AB866;
}
.tile--yellow {
  background-color: #FFA000;
}

.app .grid .row {
  height: 100px;
  display: flex;
}
.app .grid .row:not(:last-child) {
  margin-bottom: 10px;
}
.app .grid .row .grid-item {
  width: 100px;
}
.app .grid .row .grid-item:not(:last-child) {
  margin-right: 10px;
}
            </style>
            <div class="app">
              <div class="grid">
                <div class="row">
                  {% for item in menu.main_menu %}
                      {% if  item.id in user_menus %}
                      <div class="text-center">

                        <div class="rounded-circle  grid-item tile {{item.color_class}}">
                          <a
                          href="/home?open={{item.url}}" >
                            <ion-icon name="{{item.icon_class}}" style="
                            width: 100%;
                            padding-top: 8px;
                            "></ion-icon>

                          </a>
                        </div>
                        <label >{{item.name}}</label>
                      </div>
                        {% endif %} 
                    {% endfor %} 
                  <!-- <div class="rounded-circle  grid-item tile tile--orange">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div>
                  <div class="rounded-circle  grid-item tile tile--green">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div>
                  <div class="rounded-circle  grid-item tile tile--blue">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div>
                  <div class="rounded-circle  grid-item tile tile--green">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div>
                  <div class="rounded-circle  grid-item tile tile--blue">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div>
                  <div class="rounded-circle  grid-item tile tile--red">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div>
                  <div class="rounded-circle  grid-item tile tile--orange">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div>
                  <div class="rounded-circle  grid-item tile tile--red">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div>
                  <div class="rounded-circle  grid-item tile tile--blue">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div>
                  <div class="rounded-circle  grid-item tile tile--orange">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div>
                  <div class="rounded-circle  grid-item tile tile--green">
                    <ion-icon name="people-circle-outline"></ion-icon>
                  </div> -->
                </div>
              </div>
            </div>



            
          </div>
        </form>
      </div>
      <div
        class="col-4"
        style="
          height: 100vh;
          background: rgb(255 255 255 / 65%);
          box-sizing: border-box;
          padding-top: 4px;
        "
      >
        <div class="card-header text-center">
          <a href="#" class="h1">Announcements</a>
        </div>
        {% if announcements %}
        <div
          class="announcements"
          style="width: 100%; height: 90%; box-sizing: border-box"
        >
          <div
            class=""
            style="
              width: 100%;
              height: 100%;
              box-sizing: border-box;
              marging: 16px;
              padding: 32px;
            "
          >
            <marquee
              direction="up"
              scrollamount="4"
              style="
                width: 100%;
                height: 100%;
                box-sizing: border-box;
                marging: 16px;
                padding: 32px;
              "
            >
              <h2 class="font-italic">
                <ul>
                  {% for announcement in announcements %}
                  <li>{{ announcement.text }}</li>
                  {% endfor %}
                </ul>
              </h2>
            </marquee>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </body>
</html>

core/templates/core/close_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style='text-align:center'> Use only one Sample Proj tab; multiple tabs are not supported. </h1>
    <h3 style='text-align:center'> If only one tab is opened , <a href="/logout">click here</a> to logout. </h3>
</body>
</html>

core/templates/core/list-template.html
{% extends 'base.html' %} {% load static %} {% block css_files %}
<style>
  .dt-buttons.btn-group.flex-wrap {
    float: right;
  }
</style>
{% endblock %} {% block content %}

<div class="border rounded m-5 px-5 py-2">
  <div class="">
    <h2>All templates</h2>
    <table class="table border table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Has lines</th>
          <th scope="col">Active</th>
          <th scope="col">View</th>
          <th scope="col">Load</th>
        </tr>
      </thead>
      <tbody>
        {% for line in lines %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{line.template_name}}</td>
          <td>{{line.has_lines|yesno:"yeah,no"}}</td>
          <td>{{line.active|yesno:"yeah,no"}}</td>
          <td>
            <a
              href="{% url 'core:template-view' %}?template_name={{line.template_name}}"
              >view</a
            >
          </td>
          <td>
            <button
              class="btn btn-info"
              onclick='loadTemplate("{{line.template_name}}")'
            >
              Load
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div
    class="border rounded p-2 mt-3 d-flex justify-content-center"
    style="display: none !important"
    id="view-template-container"
  >
    <div id="print-div" style="width: auto; height: auto"></div>
  </div>
</div>

{% endblock %}
<!-- Custom Javascript of page -->
{% block js_files %} 
{% include 'components/datatableheadercomp.html' %} 
{% include 'components/datatablecomp.html' %} 
{% include 'components/viewrowsidebarcomp.html' %} 
{% include 'components/editviewcomponent.html' %} 
{% include 'components/selectaccountcomp.html' %} 
{% include 'components/columnsettingcomp.html' %}

<script>
  const loadTemplate = (templateName) => {
    axios
      .post(`{% url 'core:template-api' %}`, {
        template_name: templateName,
        header_context: {
          'dept': 'neeenwnww222222',
          'numb': 33,
          'date': '23/111',
          'cust_name': 'Tabish new n2222',
          'cust_code': '123',
          'tel': 808729,
          'addr': 'pune',
          'total_aed': 11000000,
          'from': 'Tabish',
          'sum_aed': 10100101,
          },
          data_list: [
            {
              'serial': 1,
              'bank': 'SBI',
              'cheque': 101,
              'due_date': '10/10',
              'invoice': 1001,
              'amount': 101,
          },
          {
              'serial': 2,
              'bank': 'SBI2',
              'cheque': 102,
              'due_date': '11/11',
              'invoice': 1002,
              'amount': 102,
          },
          {
              'serial': 3,
              'bank': 'SBI3',
              'cheque': 103,
              'due_date': '12/12',
              'invoice': 1003,
              'amount': 103,
          }
          ]})
      .then((response) => {
        $('#print-div').html(response.data.html)
        $('#view-template-container').css('display', 'block');
        })
      .catch((err) => {
        console.log(err.message, err);
      });
  };
</script>

{% endblock %}

core/templates/core/print-template.html
{% extends 'base.html' %}
{% load static %}
{% block css_files %}
<style>
   .dt-buttons.btn-group.flex-wrap {
   float: right;
   }
</style>
{% endblock %}
{% block content %}

<div class="border rounded m-5 p-5">
    <div class="d-flex justify-content-center">
        <div id='print-div' style="width: auto; height: auto;">
            {{html|safe}}
        </div>
    </div>
    <!-- <div class="d-flex justify-content-center mt-2">
        <button onclick="window.print()" class="btn btn-outline-secondary">Print</button>
    </div> -->
</div>



{% endblock %}
<!-- Custom Javascript of page -->
{% block js_files %}

{% include 'components/datatableheadercomp.html' %}
{% include 'components/datatablecomp.html' %}
{% include 'components/viewrowsidebarcomp.html' %}
{% include 'components/editviewcomponent.html' %}
{% include 'components/selectaccountcomp.html' %}
{% include 'components/columnsettingcomp.html' %}

<script>
    

</script>

{% endblock %}

core/templates/core/save-template-form.html
{% extends 'base.html' %}
{% load static %}
{% block css_files %}
<style>
   .dt-buttons.btn-group.flex-wrap {
   float: right;
   }
</style>
{% endblock %}
{% block content %}

<div >
    <div class="border rounded m-5 p-5">
        <form onsubmit="saveTemplate(event)" id="template-form">
            <div class="form-group">
                <label>Template Name</label>
                <input class="form-control" name="template_name" required/>
            </div>
            <div class="form-group">
                <input name="has_lines" type="checkbox" id="has-lines-checkbox" class="mr-2"> 
                <label for="has-lines-checkbox">Does template have lines?</label>
            </div>
            <div class="form-group d-flex align-items-center pl-0">
                <div class="custom-file col-md-3">
                    <input type="file" id="inputGroupFile01" class="custom-file-input"> 
                    <label for="inputGroupFile01" class="custom-file-label">Upload</label>
                </div> 
                <label class="ml-3">Optionally upload a copy of template word file for future references</label>
            </div>
            <div class="form-group">
                <label>Paste your template here</label>
                <div contenteditable id="html-contentt" style="height: auto;" class="mb-3 border form-control"></div>
            </div>
            <button type="submit" class="btn btn-primary">Save Template</button>
            <button class="btn btn-danger" onclick="document.getElementById('html-contentt').innerHTML=''">Reset template</button>
            <a href="{% url 'core:template-list' %}" class="btn btn-link">View All</a>
        </form>
    </div>
</div>



{% endblock %}
<!-- Custom Javascript of page -->
{% block js_files %}

{% include 'components/datatableheadercomp.html' %}
{% include 'components/datatablecomp.html' %}
{% include 'components/viewrowsidebarcomp.html' %}
{% include 'components/editviewcomponent.html' %}
{% include 'components/selectaccountcomp.html' %}
{% include 'components/columnsettingcomp.html' %}

<script>
    
    const saveTemplate = async(event) => {
        event.preventDefault()
        const form = document.querySelector('#template-form');

        const formData = new FormData();
        for (let i = 0; i < form.elements.length; i++) {
            const element = form.elements[i];
            if (element.type !== 'submit') {
                if (element.type === 'checkbox'){
                    const myCheckbox = document.getElementById('has-lines-checkbox');
                    // formData[element.name] = Boolean(myCheckbox.checked);
                    formData.append(element.name, Boolean(myCheckbox.checked));
                }
                else{
                    // formData[element.name] = element.value;
                    formData.append(element.name, element.value);
                    
                }
            }
        }
        const htmlContent = document.getElementById('html-contentt').innerHTML;
        if (htmlContent === ''){
            // toastr.error('Please paste template content')
            return false
        }
        // formData['html_content'] = htmlContent;
        formData.append('html_content', htmlContent);

        var fileInput = $('#inputGroupFile01')[0];
        if (fileInput.files.length > 0) {
            formData.append('template_file', $('#inputGroupFile01')[0].files[0]);
        }
        console.log('formData', formData);
        
        try {
            const {data: resData} = await axios.post("{% url 'core:template-save-api' %}", formData)
            console.log(resData);
        } catch (error) {
            Object.keys(error.response.data).forEach(e=>{
                console.log(`${e}: ${error.response.data[e]}`);
            })
        }
        return false
    }
</script>

{% endblock %}