ay_connect/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponse
import os

from ninja import NinjaAPI
from vehicle.api import api 

from stock_app.api import  stock_api
from Service_request.api import servicerequest_api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',namespace='core')),
   
    path('accounts/', include('accounts.urls',namespace='accounts')),
	
    path('setup/', include('setup.urls')),
  
    path('pricelist/', include('pricelist_update.urls')),

    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('stock/',include('stock_app.urls',namespace='stock')),
    path('Service_request/', include('Service_request.urls', namespace='Service_request')),
    # path('itemPublishing/',include('stock_app.urls',namespace='itemPublishing')),
    path('api/', api.urls),  
    path('api/stock/', stock_api.urls), 

    path('api/servicerequest/', servicerequest_api.urls),
 
    re_path(r'^fp/', include('django_drf_filepond.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENV != "PROD":
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

core/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import *
app_name = 'core'


urlpatterns = [
    path('', views.login, name='login'),
    path('user_announcement', views.user_announcement, name='user_announcement'),
    path('home', IframeView.as_view(), name='home_iframe'),
    path('logout', views.logout, name='logout'),
    path('get_all_columns/<model_name>', views.get_all_columns, name='get_all_columns'),
    path('get_select_options/<model_name>', views.get_select_options , name='get_select_options'),
    path('change_user_inventory/<inv_id>', views.change_user_inventory , name='change_user_inventory'),
    path('upload_product_data_dictionary/', views.upload_product_data_dictionary , name='upload_product_data_dictionary'),
    path('close_page', views.close_page, name='close_page'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" style="height: auto;">

<head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>AY  Connect | Home</title>
   {% load static %}
   <!-- Google Font: Source Sans Pro -->
   <link rel="stylesheet"
      href="{% static 'ay_connect/fonts_googleapis.css' %}">
   <!-- Font Awesome -->
   <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
   <!-- Ionicons -->
   <link rel="stylesheet" href="{% static 'ay_connect/ionicons.min.css' %}">
   <!-- Tempusdominus Bootstrap 4 -->
   <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
   <!-- iCheck -->
   <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
   <!-- JQVMap -->
   <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
   <!-- Theme style -->
   <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}">
   <!-- Custom style -->
   <link rel="stylesheet" href="{% static 'css/custom.css' %}">
   <!-- overlayScrollbars -->
   {% comment %} <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}"> {% endcomment %}
   <!-- Daterange picker -->
   <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
   <!-- summernote -->
   <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
   <!-- vueformulate Form  -->
   <link rel="stylesheet" href="{% static 'plugins/formulate/snow.min.css' %}">
   

   <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
   
   <!-- Jquery UI CSS -->
   <link rel="stylesheet" href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}">
   
   <!-- Select2 CSS -->
   <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
   <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
   <!-- DataTables -->
   <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
   <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
   <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">

   


   <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">


   <script src="{% static 'js/vue.js' %} "></script>
   <script src="{% static 'js/axios.min.js' %}"></script>

   {% block css_files %}
   {% endblock %}
  
   <script>
      var getAllColumnsUrl = '{% url 'core:get_all_columns' "test_modelname" %}'
   </script>
   <style>

      {% comment %} ::-webkit-scrollbar {
            width: 0px;
            height: 0px;
            }

      ::-webkit-scrollbar-thumb {
      border-radius: 0%;
            }

      ::-webkit-scrollbar-track {
      background-color: #f2f2f2;
            } {% endcomment %}

      tfoot.filters {
            display: table-header-group !important;
         }

   </style>
   <body class="sidebar-mini layout-fixed sidebar-collapse" data-panel-auto-height-mode="height" style="height: auto;">
      {% block content_app %} 
      {% endblock %}

      <div class="wrapper" id="app">
         <!-- Navbar -->
         <!-- <headercomp> </headercomp> -->
         
         <!-- Main Sidebar Container -->
         <!-- <sidebarmenucomp></sidebarmenucomp> -->
         

         <div class="content-wrapper "  data-loading-screen="750" style="height: 542.4px; margin-left: 0px !important;">
            {% block content %} 
            {% endblock %}
         </div>

         <!-- <footer class="main-footer d-none">
            <strong>Copyright © 2014-2021 <a href="https://adminlte.io/">AdminLTE.io</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
               <b>Version</b> 3.2.0
            </div>
         </footer>
         
         <div id="sidebar-overlay"></div> -->
         
      </div>
      
      
      
      <!-- jQuery -->
      <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

      <!-- jQuery UI 1.11.4 -->
      <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
      <!-- jquery-validation -->
      <script src="{% static 'plugins/jquery-validation/jquery.validate.min.js' %}"></script>
      <script src="{% static 'plugins/jquery-validation/additional-methods.min.js' %} "></script>
      <script>
         $.widget.bridge('uibutton', $.ui.button)
      </script>
      <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <!-- overlayScrollbars -->
       {% comment %} <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js.download' %}"></script> {% endcomment %}
      <!-- AdminLTE App -->
      <script src="{% static 'js/adminlte.js.download' %}"></script>
      
      <!-- DataTables  & Plugins -->
      <script src="{% static '/plugins/datatables/jquery.dataTables.min.js' %}"></script>
      <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
      <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
      <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
      <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
      <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
      <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
      <script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
      <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
      <script src="{% static 'plugins/datatables-colreorder/js/dataTables.colReorder.min.js' %}"></script>
 
      <!-- Form formulate plugin -->
      <script src="{% static 'plugins/formulate/formulate.min.js' %}"></script>
      
      <!-- Select2 JS -->
      <script src="{% static 'plugins/select2/js/select2.full.min.js' %} "></script>
      
      <script src="{% static 'plugins/moment/moment.min.js' %}"></script>
      <script src="{% static 'js/jquery.PrintArea.min.js' %}"></script>
      <script src="{% static 'js/toastr.min.js' %}"></script>
      <script src="{% static 'ay_connect/index.umd.js' %}"></script>

      <script src="{% static 'js/jquery.PrintArea.min.js' %}"></script>
      <script src="{% static 'js/toastr.min.js' %}"></script>
      
      <script src="{% static 'js/moment.min.js' %}"></script>
      <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>

      <script src="{% static 'js/jquery.PrintArea.min.js' %}"></script>

      <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script> -->
      <script src="{% static 'js/jspdf.min.js' %}"></script>
      <script src="{% static 'js/html2pdf.bundle.min.js' %}"></script> 
      <script src="{% static 'js/html2canvas.min.js' %}" ></script>
      {% include 'reports/pdfReport.html' %}
      
      <!-- <script src="{% static 'ay_connect/polyfills.umd.min.js' %}"></script> -->
      
      {% include 'components/layout/header.html' %}
      
      <script src="{% static 'js/toastr.min.js' %}"></script>

<!-- UNPKG -->
      {% comment %} <script src="{% static 'js/custom_plugins/index.umd.min.js' %}"></script> {% endcomment %}
      <script src="{% static 'js/custom_plugins/jquery.inputmask.min.js' %}"></script>
      <script src="{% static 'js/custom_plugins/jquery.validate.min.js' %}"></script>
      <script src="{% static 'js/custom_plugins/adminlte.min.js' %}"></script>

      <script src="{% static 'js/custom_plugins/loadingoverlay.min.js' %}"></script>

      {% include 'partials/_loading.html' %}
      

      
      {% include 'components/layout/header.html' %}
      
   <link rel="stylesheet" href="{% static 'ay_connect/flatpickr.min.css' %}" />
   <script src="{% static 'ay_connect/flatpickr.min.js' %}" ></script> 
   <script src="{% static 'ay_connect/sweetalert2.js' %}"></script>

      
      <script>

      axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
      const EventBus = new Vue();

      Vue.use(VueFormulate, {
         classes: {
             wrapper: 'form-group',
             input: 'form-control',
             inputHasErrors: 'is-invalid',
             help: 'form-text text-muted',
         }
     })

     var vAppProperties = {
         delimiters: ['[[', ']]'],
         el: '#app',
         data: {
            defaultProp : {
               header_meta : [],
               tabl_meta_data : [],
               view_meta : [],
            },
            customProp: {
            }
         },
         methods: {
         },
         mounted(){
            var self = this;
         }
   }
 

   const initDataTable=(id, settings)=>{
      if ($.fn.dataTable.isDataTable(id)) {
         var api = $(id).DataTable();
         try {
           api.clear().destroy();
         } catch (error) {
           $(id).html("");
           console.log("UNABLE TO DESTROY");
         }
       }
      //  settings.initComplete = function () {
      //       $(this).find("tfoot").remove();
      //       $(this).find("thead").after("<tfoot/>");
      //       $(this).find("tfoot").append("<tr/>");
      //       $(this).find("tfoot tr").append(settings.columns.map((x, i) =>x.title.trim() == "Action" ? "<th></th>" : "<th>" +'<input class="w-100" type="text" />' +"</th>").join(""));
      //       $(this).find("tfoot").addClass("filters");
      //       var api = this.api();

      //       api
      //       .columns()
      //       .eq(0)
      //       .each(function (colIdx) {
      //          $("input",$(".filters th").eq($(api.column(colIdx).header()).index()))
      //          .off("keyup change")
      //          .on("change", function (e) {
      //          $(this).attr("title", $(this).val());
      //          var regexr = "({search})";
      //          api
      //             .column(colIdx)
      //             .search(
      //                this.value != ""
      //                ? regexr.replace("{search}", "(((" + this.value + ")))")
      //                : "",
      //                this.value != "",
      //                this.value == ""
      //             )
      //             .draw();
      //          })
      //          .on("keyup", function (e) {
      //          e.stopPropagation();
      //          var cursorPosition = this.selectionStart;
      //          $(this).trigger("change");
      //          $(this)
      //             .focus()[0]
      //             .setSelectionRange(cursorPosition, cursorPosition);
      //          });
      //       });
      //    };

      $(id).DataTable(settings);
   }

   </script>
   {% block js_files %}
   
   {% endblock %}

   <script>
      var vApp;
      let pageProperties;
      axios.get(window.location.href)
      .then(response => {
            pageProperties = response.data
            vAppProperties.data.defaultProp.view_meta = pageProperties.view_meta
            vAppProperties.data.defaultProp.header_meta = pageProperties.header_meta;
            
            vAppProperties.data.defaultProp.tabl_meta_data = pageProperties.data_tabl_meta
            vApp = new Vue(vAppProperties);
      })
      .catch(e => {
         console.log(e)
      });
     
   </script>
</body>

</html>

templates/base_login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>ALY Reservation Process {% block title %}{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
</head>


{% block content %}



{% endblock %}


<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

</body>
</html>

templates/f_invoice.html
<!DOCTYPE html>
<html>

<head>

<title>Invoice Print  ||    {{ohid|safe}}  </title>
<script src="{% static 'js/axios.min.js' %}"></script>
<script src="{% static 'js/vue.min.js' %}"></script>



        <style>
            /** 
                Set the margins of the page to 0, so the footer and the header
                can be of the full height and width !
             **/
            @page {
                margin: 0cm 0cm;
            }

            /** Define now the real margins of every page in the PDF **/
            body {
                margin-top: 3cm;
                margin-left: 2cm;
                margin-right: 2cm;
                margin-bottom: 2cm;
            }

            /** Define the header rules **/
            header {
                position: fixed;
                top: 0cm;
                left: 0cm;
                right: 0cm;
                height: 3cm;
            }

            /** Define the footer rules **/
            footer {
                position: fixed; 
                bottom: 0cm; 
                left: 0cm; 
                right: 0cm;
                height: 2cm;
            }
        </style>
    </head>
    <body>
        <!-- Define header and footer blocks before your content -->
        <header>
            <img src="header.png" width="100%" height="100%"/>
        </header>

        <footer>
            <img src="footer.png" width="100%" height="100%"/>
        </footer>

        <!-- Wrap the content of your PDF inside a main tag -->
        <main>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            v

            <h1>Hello World</h1>
            <var></var>
            <h1>Hello World</h1><var>  <h1>Hello World</h1></var>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            v
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>  <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            v
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            v
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>

            <h1>Hello World</h1>
            <h1>Hello World</h1>  <h1>Hello World</h1>

            <h1>Hello World</h1>  <h1>Hello World</h1>

            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>  <h1>Hello World</h1>

            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>  <h1>Hello World</h1>
            <h1>Hello World</h1>

            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1>
            <h1>Hello World</h1><var>  <h1>Hello World</h1>
                <h1>Hello World</h1>
                <h1>Hello World</h1>
                <h1>Hello World</h1>
                <h1>Hello World</h1>
            <var>  <h1>Hello World</h1>
                <h1>Hello World</h1>
                <h1>Hello World</h1>
                <h1>Hello World</h1>  <h1>Hello World</h1></var></var>

                  <h1>Hello World</h1>  <h1>Hello World</h1>

                  <h1>Hello World</h1>
                  <h1>Hello World</h1>
                  <h1>Hello World</h1>
                  <h1>Hello World</h1>
                  <h1>Hello World</h1>  <h1>Hello World</h1>
                  <h1>Hello World</h1>

                    <h1>Hello World</h1>  <h1>Hello World</h1>
                    <h1>Hello World</h1>  <h1>Hello World</h1>
                    <h1>Hello World</h1>

                    <h1>Hello World</h1>
                    <h1>Hello World</h1>
                    <h1>Hello World</h1>  <h1>Hello World</h1>
                    <h1>Hello World</h1>
                    <h1>Hello World</h1>
                    <h1>Hello World</h1>
                    <h1>Hello World</h1>
                    <h1>Hello World</h1>
                    <h1>Hello World</h1>

                    <h1>Hello World</h1>  <h1>Hello World</h1>
                    <h1>Hello World</h1>
                    <h1>Hello World</h1>
                    v
                    <h1>Hello World</h1>
                    <h1>Hello World</h1>
                    <h1>Hello World</h1>

                    <h1>Hello World</h1>
                    <h1>Hello World</h1>
                    <h1>Hello World</h1>
                      <h1>Hello World</h1>
                      <h1>Hello World</h1>
                      <var>
                          <var></var>
                          <h1>Hello World</h1>  <h1>Hello World</h1>
                          <h1>Hello World</h1>
                          
                      </var>
        </main>
  

























<script>

    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";
    axios.defaults.withCredentials = true;
    
    var vInv = new Vue({
       el:'#v-invoice',
       delimiters:["[[","]]"],
       methods:{
           formatCalculation(d){
               if(d=="" || d==null || d==" ")
               {
                   d=0
               }
               return parseFloat(d).toLocaleString(undefined,{minimumFractionDigits: 2,
                                                               maximumFractionDigits: 2});
           },
       },
       mounted(){
        //showloader();
    
      
               this.base_url = window.location.origin;
               axios.post("{% url 'get-sales-inv-api' %}",{
                   ohid:"{{ohid|safe}}",              
               })
               .then(function (res) 
               {
                   // hideloader()
                   console.log(res.data)
                   vInv.invs = res.data.invs;
                   vInv.drafts = res.data.drafts;
               })
               .catch(function () 
               {
                   // hideloader()
                    alert('No Invoice Record found');
               })
       },
       data:{
           html:'',
           invs: [],
           base_url:'',
           drafts: [],
           draft_line_number:0,
           draft_line_number_2:0,
           
       }
    });
    
    </script>
</html>

templates/index.html
{% extends "base_sale.html" %}
{% load static %}


{% block content %}


      {{ request.session.user_full_name }}



<script>   
  var a= document.querySelectorAll(".nav-treeview > .nav-item > a");
  for (var i=0;i<a.length;i++)
  { 
        if(document.querySelectorAll(".nav-treeview > .nav-item > a >p")[i].innerText=='Sales')
        {
             document.querySelectorAll(".nav-treeview > .nav-item > a")[i].click();
        }
  }
</script>


{% endblock %}

templates/nav_bar.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      
    </ul>

   

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <!-- <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
             Message Start 
            <div class="media">
              <img src="{% static 'dist/img/user1-128x128.jpg' %}"  alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
           
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
           
            <div class="media">
              <img src="{% static 'dist/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
        
            <div class="media">
              <img src="{% static 'dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
         
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li> -->
    
      <!-- <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="ion ion-filing mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li> -->
      <!-- <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li> -->



    </ul>

    <ul class="navbar-nav float-right">
      <a class="dropdown-item" href="{% url 'core:logout' %}"><i class="ti-power-off m-r-5 m-l-5"></i> Log Out</a>
      <!-- ============================================================== -->
      <!-- User profile and search -->
      <!-- ============================================================== -->
      <li class="nav-item dropdown">
         
          <div class="dropdown-menu dropdown-menu-right user-dd animated">
             
          </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" id="error_tab"  data-slide="true" href="#" role="button">
          <i class="fas fa-exclamation-circle"></i>
        </a>
      </li>
      <!-- ============================================================== -->
      <!-- User profile and search -->
      <!-- ============================================================== -->
  </ul>
  </nav>