ay_connect/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.http import HttpResponse
import os

from ninja import NinjaAPI
from vehicle.api import api 

from stock_app.api import  stock_api
from Service_request.api import servicerequest_api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',namespace='core')),
   
    path('accounts/', include('accounts.urls',namespace='accounts')),
	
    path('setup/', include('setup.urls')),
  
    path('pricelist/', include('pricelist_update.urls')),

    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('stock/',include('stock_app.urls',namespace='stock')),
    path('Service_request/', include('Service_request.urls', namespace='Service_request')),
    # path('itemPublishing/',include('stock_app.urls',namespace='itemPublishing')),
    path('api/', api.urls),  
    path('api/stock/', stock_api.urls), 

    path('api/servicerequest/', servicerequest_api.urls),
 
    re_path(r'^fp/', include('django_drf_filepond.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENV != "PROD":
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

core/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import *
app_name = 'core'


urlpatterns = [
    path('', views.login, name='login'),
    path('user_announcement', views.user_announcement, name='user_announcement'),
    path('home', IframeView.as_view(), name='home_iframe'),
    path('logout', views.logout, name='logout'),
    path('get_all_columns/<model_name>', views.get_all_columns, name='get_all_columns'),
    path('get_select_options/<model_name>', views.get_select_options , name='get_select_options'),
    path('change_user_inventory/<inv_id>', views.change_user_inventory , name='change_user_inventory'),
    path('upload_product_data_dictionary/', views.upload_product_data_dictionary , name='upload_product_data_dictionary'),
    path('close_page', views.close_page, name='close_page'),

]

setup/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views


app_name = 'setup'
router = routers.DefaultRouter()
router.register(r'template_list', views.TemplateContentViewSet, basename="template_list")


urlpatterns = [
    path('api/', include(router.urls)),
    path('template',views.TemplateContentView.as_view(), name='template'),
    path('action/<action_type>/<row_id>', views.TemplateContentView.as_view(), name='template'),
    path('action/<action_type>', views.TemplateContentView.as_view(), name='template'),

    path('template-view', views.template_view , name='template-view'),
    path('template-api', views.TemplateHTMLApi.as_view() , name='template-api'),
    path('template-list', views.template_list_view , name='template-list'),
    path('template-save-api', views.TemplateSaveApi.as_view() , name='template-save-api'),
    path('conc_prog',views.ConcProgView, name='conc_prog'),
    path('conc_prog_invtr',views.ConcProgInvtrView, name='conc_prog_invtr'),
    path('conc_prog_pdf',views.ConcProgPdfView, name='conc_prog_pdf'),
    path('get-input',views.ConcProgInputDataView, name='get-input'),
    path('refresh_report',views.refresh_report, name='refresh_report'),
    path('add-concprog',views.AddConcProgView, name='add-concprog'),
    path('pdf',views.download_file, name='pdf'),
    path('email-via-template', views.TemplateHTMLEmailApi.as_view() , name='email-via-template'),
    path('exec_sql', views.ExecSql.as_view() , name='exec_sql'),

    path('customer_dms', views.CustomerDmsView.as_view(), name='customer_dms'),
    path('dms_records', views.DmsRecordsView, name='dms_records'),
    path('trip_details', views.TripDetailsView, name='trip_details'),
    path('documentation_details', views.DocumentationDetailsView, name='documentation_details'),
]

setup/views.py
import base64
import io
import json
from django.views.generic import View
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import redirect, reverse, render
from django.shortcuts import resolve_url
from ay_connect.constants import get_access_app_url
from core.endpoints import OIC_ENDPOINTS
from core.views import ActionView, BaseModelViewSet
from core.models import *
from core.utils import CrossAppAuth, get_datatable_col_info
from rest_framework import views as DRF_views, response
from .serializers import *
from .services import get_html_for_template_name
from .data import dummy_data_list, dummy_header_context
from rest_framework.parsers import MultiPartParser
from .models import *
from .serializers import *
from sequences import get_next_value
from core.services import call_oracle_api,call_oracle_api_async
from core.utils import get_loginuser_details
from accounts.email import send_async_mail_cc
from django.conf import settings
from django.http import HttpResponseServerError
from datetime import datetime
from accounts.models import ConcProgRole
from django.db import connection
import environ
env = environ.Env()

class TemplateContentView(ActionView, View):
    template_name = "setup/list-template.html"
    model = TemplateContent
    app_name = 'setup'
    sub_app_name = 'template'

    def get(self, request, action_type=None, row_id=None):
        if(action_type!=None):

            app_data = {
                    'app_name' : 'setup'
                }
            if(action_type=='add' or action_type=='edit'):
                self.template_name = "setup/add.html"
                data = self.add_form_page(app_data, action_type,row_id)
            else:
                model_data = { 
                            'model' : self.model ,
                            'title' : 'Add Template'
                            }
                data = self.page_form_elements(model_data, row_id)
        else:
            data_tabl_meta = self.template_data_list()
            header_meta = {"title": "Template",
                        "add_label": "Add Template",
                        "filter_label": "All Template",
                        "add_title" : "Add Template",
                        "add_link" : resolve_url( "setup:template", 'add'),
                        "add_unique_name" : "addTemplate"
                        }
            view_meta = {
                'row_view_url': resolve_url("setup:template", 0),
                'width': '40',
                'title': 'Add Template',
                'form_submit_url' :  resolve_url( self.app_name+':template')
            }
            data = {
                "data_tabl_meta": data_tabl_meta,
                "header_meta": header_meta,
                "view_meta": view_meta,
                'lines': TemplateContentSerializer(TemplateContent.objects.all(), many=True).data
            }
            data = data

        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse(data)

        return render(request, self.template_name, context=data)

    def post(self, request):
        post_data = json.loads(request.body)
        res = self.form_post(post_data)
        messages.success(request, 'inserted')
        return JsonResponse(res)
    
    def template_data_list(self):
        """Get Contcat list meta info
        Parameters
        ----------
        self:
            
        Returns
        -------
        json
            return enquiry list
        """
        model_name = table_name = 'TemplateContent'
        col_info = get_datatable_col_info(model_name)    
        all_column_info = col_info['column_info']
        display_col_indexes = [0, 1, 2, 4, 5, 6, 7, ]

        # custom columns defenitions
        # => column index and column html that need to overwrite while rendering
        custom_columns = {
            2: '<button type="button" class="btn btn-sm btn-block cust_class">cell_data</button>',
            5: '<button type="button" class="btn btn-sm btn-success cust_class">Download</button>',
        }
        # custom column bg colours
        cust_classes = {
            "NEW": "btn-primary",
            "QUALIFIED": "btn-success",
            "ASSIGNED": "btn-warning",
        }
        data_table_url = reverse("setup:template_list-list")
        return {
            "column_info": all_column_info,
            "table_name": table_name,
            "cust_classes": cust_classes,
            "data_table_url": data_table_url,
            #"row_view_url": row_view_url,
            "custom_columns": custom_columns,
            "display_col_indexes": display_col_indexes
        }
    
class TemplateContentViewSet(BaseModelViewSet):
    serializer_class = TemplateContentSerializer
    
    def get_queryset(self):
        return TemplateContent.objects.all()


def template_list_view(request):
    templates = TemplateContent.objects.filter(active=True)
    return render(request, 'setup/list-template.html', {'lines': templates})

def template_view(request):
    template_name = request.GET.get('template_name', None)
    if template_name:
        print('teejjjjjjjjjjjjjjjj', template_name)
        template_html = get_html_for_template_name(template_name, dummy_header_context, dummy_data_list, '')
        return render(request, 'setup/print-template.html', context={'html': template_html})
    else:
        return render(request, 'setup/save-template-form.html', context={})

# from xhtml2pdf import pisa
# from weasyprint import HTML, CSS
# from io import BytesIO
# import weasyprint
import pdfkit


# class TemplateHTMLApi(DRF_views.APIView):
#     permission_classes = ()
#     authentication_classes = ()
#     def post(self, req, *args, **kwargs):
#         template_name = req.data.get('template_name', None)
#         pdf_only = req.GET.get('pdf_only', None)
#         header_context = req.data.get('header_context', dummy_header_context)
#         data_list = req.data.get('data_list', dummy_data_list)
#         try:
#             template_html = get_html_for_template_name(template_name, header_context, data_list)
#             if pdf_only:
#                 buffer = BytesIO()

#                 # Use the buffer to receive the generated PDF
#                 pdf = pisa.CreatePDF(BytesIO(template_html.encode("UTF-8")), buffer)

#                 # If the PDF was created successfully, return it as a response
#                 if not pdf.err:
#                     response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
#                     response['Content-Disposition'] = 'attachment; filename="example.pdf"'
#                     return response

#             return JsonResponse({'html':template_html})
#         except Exception as e:
#             print(e)
#             return JsonResponse({'msg': "Template not found"}, status=400)
        
# class TemplateHTMLApi(DRF_views.APIView):
#     permission_classes = ()
#     authentication_classes = ()
#     def post(self, req, *args, **kwargs):
#         template_name = req.data.get('template_name', None)
#         pdf_only = req.GET.get('pdf_only', None)
#         header_context = req.data.get('header_context', dummy_header_context)
#         data_list = req.data.get('data_list', dummy_data_list)
#         try:
#             template_html = get_html_for_template_name(template_name, header_context, data_list)
#             if pdf_only:
#                 options = {
#                     'page-size': 'A4',
#                     'margin-top': '0mm',
#                     'margin-right': '0mm',
#                     'margin-bottom': '0mm',
#                     'margin-left': '0mm',
#                 }
#                 pdf = pdfkit.from_string(template_html, False, options=options)
#                 response = HttpResponse(pdf, content_type='application/pdf')
#                 response['Content-Disposition'] = 'attachment; filename="my_pdf.pdf"'
#                 return response
#             return JsonResponse({'html':template_html})
#         except Exception as e:
#             print(e)
#             return JsonResponse({'msg': "Template not found"}, status=400)
        
# class TemplateHTMLApi(DRF_views.APIView):
#     permission_classes = ()
#     authentication_classes = ()
#     def post(self, req, *args, **kwargs):
#         template_name = req.data.get('template_name', None)
#         pdf_only = req.GET.get('pdf_only', None)
#         header_context = req.data.get('header_context', dummy_header_context)
#         data_list = req.data.get('data_list', dummy_data_list)
#         try:
#             template_html = get_html_for_template_name(template_name, header_context, data_list)
#             if pdf_only:
#                 buffer = BytesIO()

#                 # Create the PDF object, using the buffer as its "file."
#                 weasyprint.HTML(string=template_html).write_pdf(buffer)

#                 # Get the value of the buffer.
#                 pdf = buffer.getvalue()
#                 buffer.close()

#                 # Return the PDF as a response.
#                 response = HttpResponse(pdf, content_type='application/pdf')
#                 response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'
#                 return response
#             return JsonResponse({'html':template_html})
#         except Exception as e:
#             print(e)
#             return JsonResponse({'msg': "Template not found"}, status=400)
        
# class TemplateHTMLApi(DRF_views.APIView):
#     permission_classes = ()
#     authentication_classes = ()
#     def post(self, req, *args, **kwargs):
#         template_name = req.data.get('template_name', None)
#         pdf_only = req.GET.get('pdf_only', None)
#         header_context = req.data.get('header_context', dummy_header_context)
#         data_list = req.data.get('data_list', dummy_data_list)
#         try:

setup/templates/setup/add.html
{% extends 'base.html' %}
{% load static %}
{% block css_files %}
<style>
   .dt-buttons.btn-group.flex-wrap {
   float: right;
   }
</style>
{% endblock %}
{% block content %}

<div>
     <div class="border rounded m-5 p-5">
        <form onsubmit="saveTemplate(event)" id="template-form">
            <div class="form-group">
                <label>Template Name</label>
                <input class="form-control" name="template_name" required/>
            </div>
            <div class="form-group">
                <input name="has_lines" type="checkbox" id="has-lines-checkbox" class="mr-2"> 
                <label for="has-lines-checkbox">Does template have lines?</label>
            </div>
            <div class="form-group d-flex align-items-center pl-0">
                <div class="custom-file col-md-3">
                    <input type="file" id="inputGroupFile01" class="custom-file-input"> 
                    <label for="inputGroupFile01" class="custom-file-label">Upload</label>
                </div> 
                <label class="ml-3">Optionally upload a copy of template word file for future references</label>
            </div>
            <div class="form-group">
                <label>Paste your template here</label>
                <div contenteditable id="html-contentt" style="height: auto;" class="mb-3 border form-control"></div>
            </div>
            <button type="submit" class="btn btn-primary">Save Template</button>
            <button class="btn btn-danger" onclick="document.getElementById('html-contentt').innerHTML=''">Reset template</button>
            <a href="{% url 'setup:template-list' %}" class="btn btn-link">View All</a>
        </form>
    </div> 
</div>



{% endblock %}
<!-- Custom Javascript of page -->
{% block js_files %}

{% include 'components/datatableheadercomp.html' %}
{% include 'components/datatablecomp.html' %}
{% include 'components/viewrowsidebarcomp.html' %}
{% include 'components/editviewcomponent.html' %}
{% include 'components/selectaccountcomp.html' %}
{% include 'components/columnsettingcomp.html' %}

<script>
    
    const saveTemplate = async(event) => {
        event.preventDefault()
        const form = document.querySelector('#template-form');

        const formData = new FormData();
        for (let i = 0; i < form.elements.length; i++) {
            const element = form.elements[i];
            if (element.type !== 'submit') {
                if (element.type === 'checkbox'){
                    const myCheckbox = document.getElementById('has-lines-checkbox');
                    // formData[element.name] = Boolean(myCheckbox.checked);
                    formData.append(element.name, Boolean(myCheckbox.checked));
                    
                }
                else{
                    // formData[element.name] = element.value;
                    formData.append(element.name, element.value);
                    
                }
            }
        }
        const htmlContent = document.getElementById('html-contentt').innerHTML;
        if (htmlContent === ''){
            // toastr.error('Please paste template content')
            return false
        }
        // formData['html_content'] = htmlContent;
        formData.append('html_content', htmlContent);

        var fileInput = $('#inputGroupFile01')[0];
        if (fileInput.files.length > 0) {
            formData.append('template_file', $('#inputGroupFile01')[0].files[0]);
        }
        console.log('formData', formData);
        
        try {
            const {data: resData} = await axios.post("{% url 'setup:template-save-api' %}", formData)
            console.log(resData);
        } catch (error) {
            Object.keys(error.response.data).forEach(e=>{
                console.log(`${e}: ${error.response.data[e]}`);
            })
        }
        return false
    }
</script>

{% endblock %}

setup/templates/setup/app.html
{% extends 'base.html' %}
{% load static %}
{% block css_files %}
<style>
   .dt-buttons.btn-group.flex-wrap {
   float: right;
   }
</style>
{% endblock %}
{% block content %}

<div >

  <datatableheadercomp :header_meta='defaultProp.header_meta' > </datatableheadercomp>

  <div class="tab-content">
     <!-- Content Wrapper. Contains page content -->
     <div class="">
        <!-- Main content -->
        <!-- Content Header (Page header) -->
        <div class="content-header">
           <div class="container-fluid">
              <div class="row mb-2">
                 <div class="col-sm-6">
                    <!-- <h1 class="m-0">Dashboard</h1> -->
                 </div>
                 <!-- /.col -->
                 <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                       <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
                          <li class="breadcrumb-item active">Dashboard v1</li> -->
                    </ol>
                 </div>
                 <!-- /.col -->
              </div>
              <!-- /.row -->
           </div>
           <!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <div class="card-header">
          
        </div>
        <section class="content">
           <div class="container-fluid">
              <div class="row">
                 <div class="col-12" >
                    <div class="card" >
                       <!-- /.data table -->
                       <datatablecomp  v-bind:tabl_meta_data="defaultProp.tabl_meta_data">
                       </datatablecomp>
                       <!-- /.data table -->
                    </div>
                 </div>
              </div>
        </section>
        <!-- /.content -->
        </div>

     </div>
  </div>
  <!-- action Modal -->
  <viewrowsidebarcomp :view_meta='defaultProp.view_meta'>
     <editviewcomponent :view_meta = 'defaultProp.view_meta'>  </editviewcomponent>
  </viewrowsidebarcomp>

  <columnsettingcomp>
  </columnsettingcomp>
   
</div>



{% endblock %}
<!-- Custom Javascript of page -->
{% block js_files %}

{% include 'components/datatableheadercomp.html' %}
{% include 'components/datatablecomp.html' %}
{% include 'components/viewrowsidebarcomp.html' %}
{% include 'components/editviewcomponent.html' %}
{% include 'components/selectaccountcomp.html' %}
{% include 'components/columnsettingcomp.html' %}

<script>
    
  vAppProperties.data.customProp = Object.assign(vAppProperties.data.customProp,{
      'form_meta':{}
      })
</script>

{% endblock %}

setup/templates/setup/list-template.html
{% extends 'base.html' %} {% load static %} {% block css_files %}
<style>
  .dt-buttons.btn-group.flex-wrap {
    float: right;
  }
</style>
{% endblock %} {% block content %}

<div class="border rounded m-3 p-5">
  <div class="">
    <div class="d-flex align-items-center justify-content-between py-2">
      <h2>All templates</h2>
      <button class="btn btn-success" onclick="openNewTemplateTab()">
        Create new Template
      </button>
    </div>
    <table class="table table-striped border table-bordered">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Has lines</th>
          <th scope="col">Active</th>
          <th scope="col">View</th>
          <th scope="col">Load</th>
        </tr>
      </thead>
      <tbody>
        {% for line in lines %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{line.template_name}}</td>
          <td>{{line.has_lines|yesno:"yeah,no"}}</td>
          <td>{{line.active|yesno:"yeah,no"}}</td>
          <td>
            <button
              type="button"
              onclick="openViewTemplateTab('{{line.template_name}}')"
              class="btn btn-link"
            >
              view
            </button>
          </td>
          <td>
            <button
              class="btn btn-info"
              onclick='loadTemplate("{{line.template_name}}")'
            >
              Download
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div
    class="border rounded p-2 mt-3 d-flex justify-content-center d-none"
    id="view-template-container"
  >
    <div id="print-div" class="p-5" style="width: auto; height: auto"></div>
  </div>
</div>

{% endblock %}
<!-- Custom Javascript of page -->
{% block js_files %} 
{% include 'components/datatableheadercomp.html' %} 
{% include 'components/datatablecomp.html' %} 
{% include 'components/viewrowsidebarcomp.html' %} 
{% include 'components/editviewcomponent.html' %} 
{% include 'components/selectaccountcomp.html' %} 
{% include 'components/columnsettingcomp.html' %}

<script>
  const openViewInIFrame = (data) => {
    var event = new CustomEvent("addOpenIframePage", { detail: data });
    window.parent.document.dispatchEvent(event);
  };
  const openNewTemplateTab = () => {
    const containsCreateTemplate =
      $('ul[role="tablist"]')
        .find("*")
        .filter(function () {
          return $(this).text() === "Create Template";
        }).length > 0;
    console.log("containsCreateTemplate", containsCreateTemplate);
    if (!containsCreateTemplate) {
      openViewInIFrame([
        "createTab",
        "Create Template",
        `setup/template-view`,
        "8181",
        true,
      ]);
    }
  };
  const openViewTemplateTab = (template_name) => {
    openViewInIFrame([
      "createTab",
      "View Template",
      `setup/template-view?template_name=${template_name}`,
      template_name,
      true,
    ]);
  };

  async function loadTemplate(templateName) {
    const { data } = await axios.post(`{% url 'setup:template-api' %}`, {
      template_name: templateName,
      header_context: {
        dept: "neeenwnww",
        numb: 33,
        date: "23/111",
        cust_name: "Tabish new",
        cust_code: "123",
        tel: 808729,
        addr: "pune",
        total_aed: 11000000,
        from: "Tabish",
        sum_aed: 10100101,
      },
      data_list: [
      [
        {
          'serial': 1,
          'bank': 'SBI',
          'cheque': 101,
          'due_date': '10/10',
          'invoice': 1001,
          'amount': 101,
        },
      ],
      [
        {
          'serial': 1,
          'bank': 'SBI',
          'cheque': 101,
          'due_date': '10/10',
          'invoice': 1001,
          'amount': 101,
        },
        {
            'serial': 2,
            'bank': 'SBI2',
            'cheque': 102,
            'due_date': '11/11',
            'invoice': 1002,
            'amount': 102,
        },
        {
            'serial': 3,
            'bank': 'SBI3',
            'cheque': 103,
            'due_date': '12/12',
            'invoice': 1003,
            'amount': 103,
        }
      ],
    ],
    });
    $("#view-template-container").removeClass("d-none");
    $("#print-div").empty().append(data.html);
    printPDF(data.html, 'print-div')
  }
</script>

{% endblock %}

setup/templates/setup/print-template.html
{% extends 'base.html' %}
{% load static %}
{% block css_files %}
<style>
   .dt-buttons.btn-group.flex-wrap {
   float: right;
   }
</style>
{% endblock %}
{% block content %}

<div class="border rounded m-5 p-5">
    <div class="d-flex justify-content-center">
        <div id='print-div' style="width: auto; height: auto;">
            {{html|safe}}
        </div>
    </div>
</div>



{% endblock %}
<!-- Custom Javascript of page -->
{% block js_files %}

{% include 'components/datatableheadercomp.html' %}
{% include 'components/datatablecomp.html' %}
{% include 'components/viewrowsidebarcomp.html' %}
{% include 'components/editviewcomponent.html' %}
{% include 'components/selectaccountcomp.html' %}
{% include 'components/columnsettingcomp.html' %}

<script>
    

</script>

{% endblock %}

setup/templates/setup/save-template-form.html
{% extends 'base.html' %}
{% load static %}
{% block css_files %}
<style>
   .dt-buttons.btn-group.flex-wrap {
   float: right;
   }
</style>
{% endblock %}
{% block content %}

<div >
    <div class="border rounded m-3 p-5">
        <h2>Create new Template</h2>
        <form onsubmit="saveTemplate(event)" class="border rounded p-3" id="template-form">
            <div class="form-group">
                <label>Template Name</label>
                <input class="form-control" name="template_name" required/>
            </div>
            <div class="form-group">
                <input name="has_lines" type="checkbox" id="has-lines-checkbox" class="mr-2"> 
                <label for="has-lines-checkbox">Does template have lines?</label>
            </div>
            <div class="form-group">
                <label>No of lines sections</label>
                <input class="form-control col-md-1" type="number" value="1" name="no_of_lines_sections" required/>
            </div>
            <div class="form-group">
                <input name="has_header_logo" type="checkbox" id="has_header-checkbox" class="mr-2"> 
                <label for="has_header-checkbox">Does template have a header logo?</label>
            </div>
            <div class="form-group">
                <input name="has_footer_logo" type="checkbox" id="has_footer-checkbox" class="mr-2"> 
                <label for="has_footer-checkbox">Does template have a footer logo?</label>
            </div>
            <div class="form-group d-flex align-items-center pl-0">
                <div class="custom-file col-md-3">
                    <input type="file" id="inputGroupFile01" class="custom-file-input"> 
                    <label for="inputGroupFile01" class="custom-file-label">Upload</label>
                </div> 
                <label class="ml-3">Optionally upload a copy of template word file for future references</label>
            </div>
            <div class="form-group">
                <label>Paste your template here</label>
                <div contenteditable id="html-contentt" style="height: auto;" class="mb-3 border form-control"></div>
            </div>
            <button type="submit" class="btn btn-primary">Save Template</button>
            <button class="btn btn-danger" onclick="document.getElementById('html-contentt').innerHTML=''">Reset template</button>
            <!-- <a href="{% url 'setup:template-list' %}" class="btn btn-link">View All</a> -->
        </form>
    </div>
</div>



{% endblock %}
<!-- Custom Javascript of page -->
{% block js_files %}

{% include 'components/datatableheadercomp.html' %}
{% include 'components/datatablecomp.html' %}
{% include 'components/viewrowsidebarcomp.html' %}
{% include 'components/editviewcomponent.html' %}
{% include 'components/selectaccountcomp.html' %}
{% include 'components/columnsettingcomp.html' %}

<script>
    
    const saveTemplate = async(event) => {
        event.preventDefault()
        const form = document.querySelector('#template-form');
        const formData = new FormData();
        for (let i = 0; i < form.elements.length; i++) {
            const element = form.elements[i];
            if (element.type !== 'submit') {
                if (element.type === 'checkbox'){
                    const myCheckbox = document.getElementById(element.id);
                    formData.append(element.name, Boolean(myCheckbox.checked));
                }
                else{
                    formData.append(element.name, element.value);
             }
            }
        }
        const htmlContent = document.getElementById('html-contentt').innerHTML;
        if (htmlContent === ''){
            toastr.error('Please paste template content')
            return false
        }
        formData.append('html_content', htmlContent);

        var fileInput = $('#inputGroupFile01')[0];
        if (fileInput.files.length > 0) {
            formData.append('template_file', $('#inputGroupFile01')[0].files[0]);
        }
        console.log('formData', formData);
        
        try {
            const {data: resData} = await axios.post("{% url 'setup:template-save-api' %}", formData)
            toastr.success('Saved');
        } catch (error) {
            Object.keys(error.response.data).forEach(e=>{
                toastr.error(error.response.data[e])
            })
        }
        return false
    }
</script>

{% endblock %}